---
- name: Install httpd
  hosts: all
  become: yes
  ignore_errors: true
   vars:
    datadog_api_key: "a051942312cda8191df62a021c111ca5"
    datadog_site: "datadoghq.com"
    datadog_env: "dev"
    datadog_hostname: "student-server"

  tasks:
    - name: install datadog agent